services:
  _defaults:
    autowire: true
    autoconfigure: true

  JvH\JvHPuzzelDbBundle\Migration\MigratePuzzelPlaatFormaat:
    tags:
      - { name: contao.migration, priority: 0 }
  JvH\JvHPuzzelDbBundle\Migration\MigratePuzzelProductAlias:
    tags:
      - { name: contao.migration, priority: 0 }
  JvH\JvHPuzzelDbBundle\Migration\MigratePuzzelProductAlias2:
    tags:
      - { name: contao.migration, priority: 0 }